name:                haskell-minesweeper
version:             0.1.0.0
github:              "githubuser/haskell-minesweeper"
license:             BSD3
author:              "Lucas Monteiro de Oliveira"
maintainer:          "lumonoli@hotmail.com"
copyright:           "2018 Lucas Monteiro de Oliveira"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-minesweeper#readme>

dependencies:
- base >= 4.7 && < 5
- random
- matrix
- gloss
library:
  source-dirs: src

executables:
  haskell-minesweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-minesweeper

tests:
  haskell-minesweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-minesweeper
